{% set version = '3.2.12' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-seacarb
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/seacarb_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/seacarb/seacarb_{{ version }}.tar.gz
  sha256: 7a258fd246624e510c5fc1284a9ac39285ac9ea20a72ba1cb71bf18b85aa67bd

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-gsw
    - r-oce

  run:
    - r-base
    - r-gsw
    - r-oce

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('seacarb')"           # [not win]
    - "\"%R%\" -e \"library('seacarb')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=seacarb
  license: GPL (>= 2)
  summary: Calculates parameters of the seawater carbonate system and assists the design of ocean
    acidification perturbation experiments.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: seacarb
# Title: Seawater Carbonate Chemistry
# Version: 3.2.12
# Date: 2019-03-22
# LazyData: true
# Authors@R: c(person("Jean-Pierre", "Gattuso", role = c("aut", "cre", "cph"), email = "gattuso@obs-vlfr.fr"), person("Jean-Marie", "Epitalon", role = "aut", email = "Jean-Marie.Epitalon@orange.fr"), person("Heloise", "Lavigne", role = "aut", email = "lavigne@obs-vlfr.fr"), person("James", "Orr", role = "aut", email = "james.orr@lsce.ipsl.fr"), person("Bernard", "Gentili", role = "ctb"), person("Mathilde", "Hagens", role = "ctb"), person("Andreas", "Hofmann", role = "ctb"), person("Jens-Daniel", "Mueller", role = "ctb"), person("Aurelien", "Proye", role = "ctb"), person("James", "Rae", role = "ctb"), person("Karline", "Soetaert", role = "ctb") )
# Depends: R (>= 2.10), oce, gsw
# Description: Calculates parameters of the seawater carbonate system and assists the design of ocean acidification perturbation experiments.
# Encoding: UTF-8
# URL: https://CRAN.R-project.org/package=seacarb
# License: GPL (>= 2)
# Repository: CRAN
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-03-22 08:54:11 UTC; gattuso
# Author: Jean-Pierre Gattuso [aut, cre, cph], Jean-Marie Epitalon [aut], Heloise Lavigne [aut], James Orr [aut], Bernard Gentili [ctb], Mathilde Hagens [ctb], Andreas Hofmann [ctb], Jens-Daniel Mueller [ctb], Aurelien Proye [ctb], James Rae [ctb], Karline Soetaert [ctb]
# Maintainer: Jean-Pierre Gattuso <gattuso@obs-vlfr.fr>
# Date/Publication: 2019-03-22 09:40:02 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
