travis:
  secure:
    BINSTAR_TOKEN: R+mUG/k0OSrCj4bWn2QAeUX4f7LyFZIFjRPgmFUtFb1M4Hv7Ihw0Oo9gcFY+l05dr+iApisjXHYdQ6Wg8y0c++F52wVYTPcTn0NsuTfsWGpb95GdRZkyZaEFRhv37W04qtIUO82D3mgakiuSWqdiCYYinzV7mJ47oBFrXtTt1Q0aYrcGXxIrCnCWVo0UK7XZDGJ3LBRw42aK/dBJOPIVX4mSqrm8+wyl5hj452Sq0tK8TG9FzGa6ZQ4I19ftAdDHkD0p3Sy/KyG9s+1DX5yk3yIlzFjZQ9HxcJwHdC79v3hwl03wUzdADgKyJ89W8UqoerrfBqKTMlLRalkpAasSClBAUBavGSnNHRvUuzIhMG52NWuXYxp5hYL3/Wv0D8/1DEM3lBZKWjZkfLtcTGOiW9fqWthUbHve9FqHSNBg5Ynaaml3v9P7H2hKDrfuGW9XxKwr5AVFWfVx4frB4b0Grm1+aOkPTGriOa2KM9kevDaIfsxOpLt+xq6OjNpn9IZ3Cxu2uxbLpvCfP2gQCbEApY+wia9TjY5mhTFaYTfAYV7qPhiuztn+gnYq4JRLq/2r+uRd2f7s0+k9UzO6j77l2R/PaAEoT/Gosqy3aT4VrRKz1UTRmyY+kMUiYrU5kPFYWudw4UN70BO8zgDGm6iVKAUdVJ3YFsLic62Rl9pAZTY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
