travis:
  secure:
    BINSTAR_TOKEN: l4KM5Pp/dBLokEQNXvT9IMA63UFrHY+2lKgqZm9DHQfabAOiT6koQvkTRcimhto03i3/i8GvuVEd6SgKm1cfjY71RdjLrFEiIF5aBJoS1wTGekn2TU5MYfs0Ts1rVbwnp2snKDGe8wrEd2h8SKcDu5dg2gqu1oPJPnI//7itAR8CnqIO0oOY93I3L4Wmn9P1dxJfVzilv30a4FgkwLN6/QrzWmMN7pocx0hPXqsO56Qxs5KylvZlJDMfExND9n0POw033I5mFnPBLF6fILo6PHvxvvnVuUA8h2UptR/PGsX1PaiZGCE61WevldnPNz5l7qBlBAAUkoMUuse/RLKLKNhPi1Ur13/uzACGlwXm1VcVerhZS0kEH/ysp1oJga6WhYiMzF69Atca7VZn6TFcubtgolxN91LH0fxACro2EbpUNyHOSRsc+Gin0qjoWtk9dfKDom6YUCMmQTPGPvh6fQZHt/HzwKLLQYn0uhmvYHhOEXdLXqzu4WcJq8yY/QF/cvVbnArTsOKJsV4dy/PnKwFVzu7ZjYlZKlgOgof0teiWdyTlqvEvqCCTb7js2mq96T39CZpW9D0p7DMeZ1DkoKkd35/id62BPmThF5g9jZwXcdsqoumwuGlQM88Kt5FyqLHES6Bb2uYoDvZrx2Qb9m4Xr3hM5UIDJNiC6o6ZQ+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
