travis:
  secure:
    BINSTAR_TOKEN: H/9Ik+L8YC9i8/F0CT2ib0elkntt3qzlJ3skpQ22e9XwUiFiqCk9PoiaZKyRNd/1mfgEhorQ1peDrz0DV91Z9ExlkM77+X1N97oULeOFQ3noSzPAqWqv5HU9gvgln17gtFSCGKkGiiP6alaQ05N9sYtnALQVA/5hsCGwX7K//qquBYeKNKo7+bWQN/qYQgorlBL5DXHhLot3EkQbDCIJ6q94H8u2E0eS+9zAEGVPRZtVb1VkiW6huC2n6ykbGGIc6N7EWunb50/f26YIpBqyicF0QFUCphjlbQg/mkNj3Y28JMmP+CMV71b8u4nVYaprMftqpt3WJzt944XCbhl+06XBZHIZ7rbQOt8ZUiY1TBx3RZUBH+9zHI2rCOuhTSlrxvfLQqxxdwYeGz7NCTCrY0VTn4b1I834VTykbf5KPMTBZetG0H2DxiDUDjojlBJ45pgz39ezeFNi3iFo06wah7NUwK4TEUenj1mTy4QDBzirLwaFfy/9unlYI5rmljWdu72rwo4ebmTN6yPxZ4quMjd5RWAF3s4368j5KxqXIs+b1dB2T/CRzkXNz7ewtCaHEMP9BA/krPhmvmccNWwabn7AaUqTEEMptaNyrB/nwlBgq14By+44ZMvJuOq2DxqIqBVa1yX6SO2j56UAmQVZtD6VzdZZJSJwMpx/oRZ9M54=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
